package com.github.igarashitm.issues.soap.signencrypt.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.18.redhat-1
 * 2016-04-27T13:12:10.380+09:00
 * Generated source version: 2.7.18.redhat-1
 * 
 */
@WebService(targetNamespace = "http://signencrypt.soap.issues.igarashitm.github.com/", name = "FaultService")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface FaultService {

    @WebMethod
    @WebResult(name = "invokeResponse", targetNamespace = "http://signencrypt.soap.issues.igarashitm.github.com/", partName = "invokeResponse")
    public java.lang.Object invoke(
        @WebParam(partName = "invoke", name = "invoke", targetNamespace = "http://signencrypt.soap.issues.igarashitm.github.com/")
        java.lang.Object invoke
    );
}
