package com.github.igarashitm.issues.soap.signencrypt.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.18.redhat-1
 * 2016-04-27T13:12:10.417+09:00
 * Generated source version: 2.7.18.redhat-1
 * 
 */
@WebServiceClient(name = "FaultServiceService", 
                  wsdlLocation = "http://127.0.0.1:8080/soap-signencrypt-fault-2.1.0-SNAPSHOT/FaultService?wsdl",
                  targetNamespace = "http://signencrypt.soap.issues.igarashitm.github.com/") 
public class FaultServiceService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://signencrypt.soap.issues.igarashitm.github.com/", "FaultServiceService");
    public final static QName FaultServicePort = new QName("http://signencrypt.soap.issues.igarashitm.github.com/", "FaultServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://127.0.0.1:8080/soap-signencrypt-fault-2.1.0-SNAPSHOT/FaultService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(FaultServiceService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://127.0.0.1:8080/soap-signencrypt-fault-2.1.0-SNAPSHOT/FaultService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public FaultServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public FaultServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FaultServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public FaultServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public FaultServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public FaultServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns FaultService
     */
    @WebEndpoint(name = "FaultServicePort")
    public FaultService getFaultServicePort() {
        return super.getPort(FaultServicePort, FaultService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FaultService
     */
    @WebEndpoint(name = "FaultServicePort")
    public FaultService getFaultServicePort(WebServiceFeature... features) {
        return super.getPort(FaultServicePort, FaultService.class, features);
    }

}
